plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.offlinecontroller'
    compileSdk 33

    defaultConfig {
        applicationId "com.example.offlinecontroller"
        minSdk 26
        targetSdk 33
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
